module.exports = {
  ids: {
    app: "app",
    adminPanel: "adminPanel",
    adminPanelHome: "adminPanelHome",
    userPanel: "userPanel",
    userPanelHome: "userPanelHome",
    company: "company",
    managePreferences: "managePreferences",
    manageAreas: "manageAreas",
    manageWarrantyNotes: "manageWarrantyNotes",
    customers: "customers",
    manageCustomers: "manageCustomers",
    salesmen: "salesmen",
    manageSalesmen: "manageSalesmen",
    products: "products",
    manageProducts: "manageProducts",
    manageProductBatches: "manageProductBatches",
    manageProductCustomerPrices: "manageProductCustomerPrices",
    invoice: "invoice",
    makeInvoice: "makeInvoice",
    invoiceRecord: "invoiceRecord",
    payments: "payments",
    manageCustomerPayments: "manageCustomerPayments",
    reports: "reports",
    saleAndStockReport: "saleAndStockReport",
    customerLedgerReport: "customerLedgerReport",
    changePassword: "changePassword",
    logout: "logout",
    support: "support",
    about: "about",
    devTools: "devTools",
    quit: "quit",
  },
  labels: {
    adminPanel: "Admin Panel",
    adminPanelHome: "Home",
    userPanel: "User Panel",
    userPanelHome: "Home",
    company: "Company",
    managePreferences: "Preferences",
    manageAreas: "Manage Areas",
    manageWarrantyNotes: "Manage Warranty Notes",
    customers: "Customers",
    manageCustomers: "Manage Customers",
    salesmen: "Salesmen",
    manageSalesmen: "Manage Salesmen",
    products: "Products",
    manageProducts: "Manage Products",
    manageProductBatches: "Manage Product Batches (Inventory)",
    manageProductCustomerPrices: "Manage Product Customer Prices",
    invoice: "Invoice",
    makeInvoice: "Make Invoice",
    invoiceRecord: "Invoice Record",
    payments: "Payments",
    manageCustomerPayments: "Manage Customer Payments",
    reports: "Reports",
    saleAndStockReport: "Sale && Stock (SSR)",
    customerLedgerReport: "Customer Ledger",
    changePassword: "Change Password",
    logout: "Logout",
    support: "Support",
    about: "About",
    devTools: "Developer Tools",
    quit: "Quit",
  },
  roles: {
    about: "about",
    devTools: "toggleDevTools",
    quit: "quit",
  },
  types: {
    separator: "separator",
    normal: "normal",
    checkbox: "checkbox",
    radio: "radio",
    submenu: "submenu",
  },
};
